baseURL = 'https://micheledinelli.github.io/ips-config'
languageCode = 'en-us'
title = 'IPS'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

    [params]

        [params.footer]
            copyright = "© Michele Dinelli"

        [params.social]
            github = "micheledinelli/ips-config"

        [params.docs]
            darkMode = true
        
    [menu]
    [[menu.primary]]
        name  = "Docs"
        url = "docs/"
        identifier = "docs"
        weight = 10